package pacman;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import pacman.base.Util;

import static org.junit.Assert.*;

public class PacmanTest {
    @Test public void testUtil() {
    	Util.log("Util test");
        assertTrue(true);
    }
}
